[font]
normal = { family = "Monospace", style = "Regular" }
size = 12

[window]
# startup_mode = "windowed"
padding = { x = 10, y = 10 }

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "Insert", mods = "Shift", action = "paste" }]
